# Identify the SonarQube Cloud project that will receive the analysis results.
sonar.projectKey=Tevinar_social_app

# Identify the SonarQube Cloud organization that owns the project.
sonar.organization=tevinar

# Define the directory containing the main source code to analyze.
sonar.sources=lib

# Define the directory containing the test code for the project.
sonar.tests=test

# Tell SonarQube Cloud where the Flutter LCOV coverage report is generated.
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Exclude files and folders from SonarQube coverage reporting.
sonar.coverage.exclusions=\
lib/app/bootstrap/**,\
lib/app/logging/**,\
lib/app/router/**,\
lib/core/config/**,\
lib/core/constants/**,\
lib/core/network/**,\
lib/core/services/**,\
lib/core/theme/**,\
lib/core/usecases/**,\
lib/core/widgets/**