# Identify the SonarQube Cloud project that will receive the analysis results.
sonar.projectKey=Tevinar_social_app

# Identify the SonarQube Cloud organization that owns the project.
sonar.organization=tevinar

# Define the directory containing the main source code to analyze.
sonar.sources=lib

# Define the directory containing the test code for the project.
sonar.tests=test
